language: python

python:
  - "3.6"

matrix:
    include:
    - env: MK_ARGS=""
    - env: MK_ARGS=fortran

before_install:
  - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")

addons:
   apt:
      packages:
      - gfortran
      - libgmp-dev
      - libmpfr-dev

install:
  - pip install -r requirements.txt

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export PYRO_HOME=$(pwd)
  - ./mk.sh $MK_ARGS

script:
  - flake8 --ignore=W504,F403,E226,E126,E127,E128,E129,E241,E741 .
  - pytest -v --cov=. --cov-config .coveragerc --nbval --ignore=docs --ignore=./multigrid/variable_coeff_elliptic.ipynb --ignore=examples/mesh --ignore=examples/multigrid
#   - travis-sphinx build

# after_success:
#   - travis-sphinx deploy

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   keep-history: true
#   on:
#     branch: master
